#! /bin/sh

sxhkd &

bspc monitor LVDS-1 -d I II III IV V
bspc monitor VGA-1 -d VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt:sxhkd_help state=floating

compton &
~/.config/polybar/launch.sh &
urxvt -e sh -c ". ~/.env && wtf" &
