#! /bin/sh

sxhkd &

~/.config/bspwm/monitors

bspc config border_width        0
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true

bspc rule -a URxvt:sxhkd_help state=floating
bspc rule -a URxvt:calendar state=floating
bspc rule -a Firefox:Toolkit state=floating

compton &
urxvt -e wtf &
