#!/bin/bash
if [[ $(mons | grep Monitors | cut -d : -f 2) -le 1 ]]
then
    bspc monitor -d I II III IV V VI VII VIII
else
    bspc monitor $MON_PRIMARY -d I II III IV V
    bspc monitor $MON_SECONDARY -d VI VII VIII IX X
fi

~/.config/polybar/launch.sh &

killall -q wall_theme 
wall_theme -p Mojave/ -c 17 &
