#!/bin/bash
[[ $MONS_NUMBER ]] || export MONS_NUMBER=$(mons | grep Monitors | cut -d : -f 2)

monitors=0
if [[ "$1" = "-1" ]]
then
    monitors=1
fi

echo \"$1\"

#if [[ $(mons | grep Monitors | cut -d : -f 2) -le 1 ]]
if [ $MONS_NUMBER -le 1 ] || [ $monitors -eq 1 ]
then
    bspc monitor -d I II III IV V VI VII VIII
else
    export MON_SECONDARY=$(mons | grep enabled | grep -v '*' | tail -1 | cut -d: -f2 | tr -d ' ' | cut -d'(' -f1)
    bspc monitor $MON_PRIMARY -d I II III IV V
    bspc monitor $MON_SECONDARY -d VI VII VIII IX X
fi

if [[ -f "$HOME/.config/polybar/config.ini" ]]
    . $HOME/.config/polybar/launch.sh &
fi

if [[ -f "$HOME/.config/eww/eww.yuck" ]]
    eww daemon &
fi

killall -q wall_theme 
wall_theme -p debian -s .png -c 1 &
