wtf:
  colors:
    border:
      focusable: "dimgray"
      focused: "darkslategray"
      normal: "dimgray"
    checked: "dimgray"
    highlight:
      fore: "#4D4D4D"
      back: "#50FA7B"
    labels: "#50FA7B::b"
    rows:
      even: "#5AF78E"
      odd: "#50FA7B"
    subheading: "#50FA7B::b"
    text: "#5AF78E"
    title: "#50FA7B"
  mods:
    todo:
      enabled: true
      filename: "todo.yml"
      checkedIcon: "X"
      colors:
        checked: "#BFBFBF"
      format: true
      position:
        top: 0
        left: 0
        height: 13
        width: 2
      wrapText: false
      refreshInterval: 3600
      title: "To-Do"
    git:
      commitCount: 5
      repositories:
        - "/home/mfr/notes"
        - "/home/mfr/dotfiles"
      enabled: true
      position:
        top: 0
        left: 2
        height: 20
        width: 2
      refreshInterval: 15
    logo:
      enabled: false
      focusable: false
      type: cmdrunner
      cmd: "neofetch"
      args: ["-L"]
      position:
        top: 0
        left: 2
        height: 20
        width: 2
      refreshInterval: 14400
      title: "OS"
    calendar:
       enabled: false
       focusable: true
       type: cmdrunner
       cmd: "khal"
       args: ["list", "now"]
       position:
         top: 0
         left: 2
         height: 13
         width: 2
       refreshInterval: 600
       title: "Calendar"
    hackernews:
      enabled: true
      numberOfStories: 20
      position:
        top: 0
        left: 4
        height: 13
        width: 3
      refreshInterval: 1800
      title: "Hacker News"
    exchangerates:
      enabled: false
      rates:
        USD:
          - "CZK"
        EUR:
          - "CZK"
        GBP:
          - "CZK"
      position:
        top: 13
        left: 0
        height: 7
        width: 2
      refreshInterval: 60
      title: "Exchange"
    yfinance:
      enabled: true
      symbols:
        - "AAPL"
        - "CZK=X"
        - "EURCZK=X"
        - "DOT-USD"
      colors:
        bigup: "#50FA7B"
        up: "#5AF78E"
        bigdrop: "#FF5555"
        drop: "#FF6E67"
      position:
        top: 13
        left: 0
        height: 7
        width: 2
      sort: true
      refreshInterval: 60
      title: "Finance"
    power:
      enabled: true
      position:
        top: 13
        left: 4
        height: 7
        width: 3
      refreshInterval: 30
      title: "Power"
    travisci:
      enabled: false
      position:
        top: 13
        left: 4
        height: 7
        width: 3
      sort_by: "finished_at:desc"
      compact: true
      pro: true
      refreshInterval: 300
    digitalclock:
      enabled: true
      font: digitalfont
      color: "#30FA7B"
      position:
        top: 20
        left: 0
        height: 9
        width: 2
      refreshInterval: 15
      title: "Time"
    prettyweather:
      city: "Kolin"
      enabled: true
      position:
        top: 20
        left: 2
        height: 9
        width: 2
      refreshInterval: 1800
      title: "Weather"
    ipapi:
      colors:
        name: "#50FA7B"
        value: "#E6E6E6"
      args:
        - "ip"
        - "organization"
        - "city"
        - "country"
        - "coordinates"
        - "timezone"
      enabled: true
      position:
        top: 20
        left: 4
        height: 9
        width: 3
      refreshInterval: 60
      title: "IP info"
    ipinfo:
      colors:
        name: "#50FA7B"
        value: "#E6E6E6"
      enabled: false
      position:
        top: 20
        left: 4
        height: 9
        width: 3
      refreshInterval: 60
      title: "IP info"
    firewall:
      enabled: true
      type: cmdrunner
      cmd: "ufw"
      args: ["show","listening"]
      position:
        top: 29
        left: 0
        height: 12
        width: 2
      refreshInterval: 30
      title: "Open ports"
    resourceusage:
      enabled: true
      cpuCombined: false
      position:
        top: 29
        left: 2
        height: 12
        width: 2
      refreshInterval: 5
      title: "Resources"
    urlcheck:
      enabled: true
      urls:
        - "https://www.m-fr.cz"
        - "https://example.com"
      position:
        top: 29
        left: 4
        height: 4
        width: 3
      refreshInterval: 30
      title: "URL check"
    disk:
      enabled: true
      type: cmdrunner
      cmd: "df"
      args: ["-h", "-x", "squashfs"]
      position:
        top: 33
        left: 4
        height: 8
        width: 3
      refreshInterval: 30
      title: "Disk usage"
    version:
      enabled: true
      border: false
      focusable: false
      type: cmdrunner
      cmd: "wtfutil"
      args: ["-v"]
      color: lime
      position:
        top: 41
        left: 0
        height: 1
        width: 2
      refreshInterval: 0
      title: "Version"
    feedreader:
      enabled: true
      border: false
      focusable: false
      feeds:
      - "https://github.com/wtfutil/wtf/releases.atom"
      feedLimit: 1
      position:
        top: 41
        left: 2
        height: 1
        width: 2
      refreshInterval: 3600
      title: "WTF releases"
    uptime:
      enabled: true
      border: false
      focusable: false
      type: cmdrunner
      cmd: "uptime"
      args: ["-p"]
      position:
        top: 41
        left: 4
        height: 1
        width: 3
      refreshInterval: 15
      title: "Uptime"
