wtf:
  colors:
    border:
      focusable: "dimgray"
      focused: "darkslategray"
      normal: "dimgray"
    checked: "dimgray"
    highlight:
      fore: "black"
      back: "green"
    labels: "green::b"
    rows:
      even: "lime"
      odd: "lightgreen"
    subheading: "lightgreen::b"
    text: "lime"
    title: "green"
  grid:
    columns: [38, 38]
    rows: [13, 6, 9, 11]
  mods:
    todo:
      enabled: true
      filename: "todo.yml"
      checkedIcon: "X"
      colors:
        checked: "gray"
      format: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      wrapText: false
      refreshInterval: 3600
      title: "To-Do"
    logo:
      enabled: true
      focusable: false
      type: cmdrunner
      cmd: "screenfetch"
      args: ["-L"]
      position:
        top: 0
        left: 1
        height: 2
        width: 1
      refreshInterval: 14400
      title: "OS"
    hackernews:
      enabled: true
      numberOfStories: 20
      position:
        top: 0
        left: 2
        width: 1
        height: 1
      refreshInterval: 1800
      title: "Hacker News"
    exchangerates:
      enabled: true
      rates:
        USD:
          - "CZK"
        EUR:
          - "CZK"
      position:
        top: 1
        left: 0
        width: 1
        height: 1
      refreshInterval: 60
      title: "Exchange"
    feedreader:
      enabled: true
      focusable: false
      feeds:
      - https://wtfutil.com/blog/index.xml
      feedLimit: 3
      position:
        top: 1
        left: 2
        width: 1
        height: 1
      refreshInterval: 3600
      title: "WTF releases"
    digitalclock:
      enabled: true
      font: digitalfont
      color: lime
      position:
        top: 2
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      title: "Time"
    prettyweather:
      city: "Kolin"
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 1800
      title: "Weather"
    power:
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 30
      title: "Power"
    ipinfo:
      colors:
        name: "red"
        value: "lime"
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 60
      title: "IP info"
    resourceusage:
      enabled: true
      cpuCombined: false
      position:
        top: 3
        left: 1
        height: 1
        width: 1
      refreshInterval: 5
      title: "Resources"
    disk:
      enabled: true
      type: cmdrunner
      cmd: "df"
      args: ["-h"]
      position:
        top: 3
        left: 2
        height: 1
        width: 1
      refreshInterval: 30
      title: "Disk usage"
    uptime:
      enabled: true
      focusable: false
      type: cmdrunner
      cmd: "uptime"
      args: ["-p"]
      color: lime
      position:
        top: 4
        left: 0
        height: 1
        width: 2
      refreshInterval: 15
      title: "Uptime"
    version:
      enabled: true
      focusable: false
      type: cmdrunner
      cmd: "wtf"
      args: ["-v"]
      color: lime
      position:
        top: 4
        left: 2
        height: 1
        width: 1
      refreshInterval: 0
      title: "Version"
